-- schema.sql
-- -----------
-- AgriIndex SQLite database schema.
--
-- Tables
-- ------
--   urls             – Every unique URL ever seen (canonical form)
--   pages            – Full page content and extracted metadata
--   entities         – Unique named entities extracted by spaCy
--   page_entities    – Many-to-many link between pages and entities
--   contacts         – Emails and phone numbers found on pages
--   search_discovery – Records each URL's first discovery via a DDG query

-- ---------------------------------------------------------------------------
-- urls
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS urls (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    url            TEXT    NOT NULL,          -- raw URL as returned by DDG / links
    canonical_url  TEXT    NOT NULL UNIQUE,   -- normalised, deduplicated form
    domain         TEXT    NOT NULL,
    first_seen     TEXT    NOT NULL,          -- ISO-8601 UTC timestamp
    last_crawled   TEXT,                      -- ISO-8601 UTC timestamp, nullable
    crawl_count    INTEGER NOT NULL DEFAULT 0,
    is_blocked     INTEGER NOT NULL DEFAULT 0  -- 1 if domain is on block list
);

CREATE INDEX IF NOT EXISTS idx_urls_domain        ON urls (domain);
CREATE INDEX IF NOT EXISTS idx_urls_canonical_url ON urls (canonical_url);

-- ---------------------------------------------------------------------------
-- pages
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pages (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    url_id           INTEGER NOT NULL REFERENCES urls (id) ON DELETE CASCADE,
    fetched_at       TEXT    NOT NULL,  -- ISO-8601 UTC timestamp
    http_status      INTEGER,
    page_title       TEXT,
    meta_description TEXT,
    cleaned_text     TEXT,
    word_count       INTEGER,
    summary          TEXT,             -- generated by llama.cpp
    topics           TEXT,             -- JSON array of topic strings
    keywords         TEXT,             -- JSON object: {set_name: hit_count, …}
    relevance_cornbelt_ai REAL,        -- 0.0 – 1.0
    relevance_investor    REAL,        -- 0.0 – 1.0
    page_type        TEXT,             -- e.g. "news", "product", "research", …
    content_hash     TEXT              -- SHA-256 of cleaned_text for deduplication
);

CREATE INDEX IF NOT EXISTS idx_pages_url_id       ON pages (url_id);
CREATE INDEX IF NOT EXISTS idx_pages_content_hash ON pages (content_hash);

-- ---------------------------------------------------------------------------
-- entities
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS entities (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    text        TEXT NOT NULL,
    label       TEXT NOT NULL,          -- spaCy entity label, e.g. ORG, GPE, PERSON
    UNIQUE (text, label)
);

-- ---------------------------------------------------------------------------
-- page_entities
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS page_entities (
    page_id   INTEGER NOT NULL REFERENCES pages (id)    ON DELETE CASCADE,
    entity_id INTEGER NOT NULL REFERENCES entities (id) ON DELETE CASCADE,
    count     INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (page_id, entity_id)
);

-- ---------------------------------------------------------------------------
-- contacts
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS contacts (
    id       INTEGER PRIMARY KEY AUTOINCREMENT,
    page_id  INTEGER NOT NULL REFERENCES pages (id) ON DELETE CASCADE,
    type     TEXT    NOT NULL,  -- "email" or "phone"
    value    TEXT    NOT NULL,
    UNIQUE (page_id, type, value)
);

CREATE INDEX IF NOT EXISTS idx_contacts_page_id ON contacts (page_id);

-- ---------------------------------------------------------------------------
-- search_discovery
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS search_discovery (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    url_id       INTEGER NOT NULL REFERENCES urls (id) ON DELETE CASCADE,
    query        TEXT    NOT NULL,   -- the DDG query string that found this URL
    result_rank  INTEGER,            -- position in the search result list (1-based)
    discovered_at TEXT   NOT NULL    -- ISO-8601 UTC timestamp
);

CREATE INDEX IF NOT EXISTS idx_search_discovery_url_id ON search_discovery (url_id);
CREATE INDEX IF NOT EXISTS idx_search_discovery_query  ON search_discovery (query);
